# Path to the data npz file
data_path: data_debug/train_dataset_vertex_eq_dist_debug.npz

# Random seed
random_seed: 13

# Count of epochs:
epochs: 5

# Batch size
batch_size: 32

# Debug mode
debug: True

autosave:
  enabled: True
  output_dir: results_debug
  file_prefix: test
  metric_monitor: val_point_in_ellipse